server:
  port: 8080

spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf-8&amp;useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;allowMultiQueries=true
    username: root
    password:

  session:
    store-type: redis

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

  freemarker:
    cache: true
    template-loader-path: classpath:/templates

  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
    user: admin
    password: admin


  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

debug: false