server:
  port: 8080

spring:

  datasource:
    url: jdbc:mysql://192.168.1.227:3307/saas?characterEncoding=utf-8&amp;useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;allowMultiQueries=true
    username: edu_user
    password: 123456

  session:
    store-type: redis

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0