server:
  port: 8080

spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf-8&amp;useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;allowMultiQueries=true
    username: root
    password: password

  session:
    store-type: redis

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0